name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config: [{name: Android, target: Android}]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.config.target }}
          
